baseURL = "https://aineed.dev/"
languageCode = "fr"
title = "Nabil AÏNAS"
description = "Découvrez le site de Nabil, dédié aux articles et projets sur les technologies cloud et les méthodes DevOps."
enableRobotsTXT = true
summaryLength = 40
canonifyURLs = true
enableGitInfo = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]

[taxonomies]
  tag = "tags"
  category = "categories"
  techno = "technos"
  series = "series"

[related]
  includeNewer = true
  threshold = 12
  toLower = true
  [[related.indices]]
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "technos"
    weight = 90
  [[related.indices]]
    name = "series"
    weight = 80
  [[related.indices]]
    name = "categories"
    weight = 70
  [[related.indices]]
    name = "keywords"
    weight = 60
  [[related.indices]]
    name = "date"
    weight = 20
    pattern = "2006"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"