baseURL = "https://github.com/nabilainas/aineed.github.io"
languageCode = "fr"
title = "AINeas"
description = "Découvrez le site de Nabil, dédié aux articles et projets sur les technologies cloud et les méthodes DevOps."
enableRobotsTXT = true
summaryLength = 0

[outputs]
  home = ["HTML", "RSS", "JSON"]