baseURL = "https://aineed.dev/"
languageCode = "fr"
title = "Aineed"
description = "Découvrez le site de Nabil, dédié aux articles et projets sur les technologies cloud et les méthodes DevOps."
enableRobotsTXT = true
summaryLength = 0

[outputs]
  home = ["HTML", "RSS", "JSON"]